Makefile: fix gcc 'undefined reference' problems
gcc is sensitive to the order in which linking flags are passed. The current argument order causes errors:

    gcc  -lgd -lm -o ansi2gif ansi2gif.o pcfont.o
    .../ansi2gif/ansi2gif.c:114: undefined reference to `gdImageColorAllocate'
    ... and more such errors ...

Moving the linking flags to the end of the invocation means `make` succeeds without errors.

    gcc  -o ansi2gif ansi2gif.o pcfont.o -lgd -lm